services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "4555:3000"
    volumes:
      - ./check-ins:/app/check-ins
    restart: unless-stopped

  scanner:
    build:
      context: .
      dockerfile: Dockerfile.scanner
    volumes:
      - ./check-ins:/app/check-ins
      - ./config.json:/app/config.json
    network_mode: host
    restart: unless-stopped
